package ua.com.CollectionsAndMap.domain;

public enum TypeRow {

    ARRAYLISTADDBEGIN,
    ARRAYLISTADDMIDDLE,
    ARRAYLISTADDEND,
    ARRAYLISTSEARCH,
    ARRAYLISTREMOVEBEGIN,
    ARRAYLISTREMOVEMIDDLE,
    ARRAYLISTREMOVEEND,
    LINKEDLISTADDBEGIN,
    LINKEDLISTADDMIDDLE,
    LINKEDLISTADDEND,
    LINKEDLISTSEARCH,
    LINKEDLISTREMOVEBEGIN,
    LINKEDLISTREMOVEMIDDLE,
    LINKEDLISTREMOVEEND,
    COPYONWRITEADDBEGIN,
    COPYONWRITEADDMIDDLE,
    COPYONWRITEADDEND,
    COPYONWRITESEARCH,
    COPYONWRITEREMOVEBEGIN,
    COPYONWRITEREMOVEMIDDLE,
    COPYONWRITEREMOVEEND,
    TREEMAPADD,
    TREEMAPSEARCHKEY,
    TREEMAPREMOV,
    HASHMAPADD,
    HASHMAPSEARCHKEY,
    HASHMAPREMOVE

    }
